### PR TITLE
Contribution Guidelines

### PR DESCRIPTION
**Pull request by bolorundurowb**
#3

### CODE REVIEW

**Comment by rowlandekemezie** [comment]
@bolorundurowb resolve conflicts.

**Comment by bolorundurowb** [comment]
I have sent a mergeable PR

**Comment by rowlandekemezie** [comment]
@bolorundurowb ☝️

**Comment by bolorundurowb** [comment]
@andela-rekemezie The new PR i sent doesnt have merging issues

**Pull request closed without merging**
